### ISSUE TITLE
Update Docker vs. R blog post

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-project.github.io#10]
Original post: http://o2r.info/2016/12/15/investigating-docker-and-R/

**This issue will be updated with changes so we can have multiple PRs realizing this.**

- [x] add shortlink http://bit.ly/docker-r to the top of the post
- [x] add link to containerit presentation and package
- [x] mention `nuest/mro` images: https://hub.docker.com/r/nuest/mro/
- [x] mention `nuest/renjin` image: https://hub.docker.com/r/nuest/renjin/
- [x] mention https://www.rdocumentation.org/packages/batchtools/versions/0.9.3
  - uses Docker Swarm as scheduler for HPC systems
  - cluster function starts Docker containers, see https://mllg.github.io/batchtools/reference/makeClusterFunctionsDocker
  - creates docker commands itself, see https://github.com/mllg/batchtools/blob/master/R/clusterFunctionsDocker.R
- [x] add link to PR with these updates to top of the post
- [x] extend information on Rocker and Bioconductor (types of images etc.)
- [x] add `sevenbridges` package
  - use Docker to create R-based CLIs, see http://www.tengfei.name/sevenbridges/vignettes/docker.html
  - use Docker for testing somehow, see https://www.rdocumentation.org/packages/sevenbridges/versions/1.2.4/topics/set_test_env
- [x] add gitlabr where you can defined the Docker base image for GitLab continuous integration tests, see https://www.rdocumentation.org/packages/gitlabr/versions/0.9/topics/gl_ci_job
- [x] ~~(not sure about this one) rodam-package requires a base software distributed in Docker image or VM, see https://www.rdocumentation.org/packages/Rodam/versions/0.1.2/topics/Rodam-package~~ only mentions you can run the ODAM server based on Docker
- [x] add `sanitizers`, which uses (Rocker) images to test compiler setups, see https://www.rdocumentation.org/packages/sanitizers/versions/0.1.0
- [x] mention https://bhaskarvk.github.io/docker/ (under dev, very new, wraps Python API so should work on Windows: https://twitter.com/bhaskar_vk/status/884404170631122944, see also https://github.com/wch/harbor/issues/11)
- [x] update link to Boettiger paper to https://dl.acm.org/citation.cfm?doid=2723872.2723882
- [x] mention https://github.com/nuest/x11rockerstudio
- [x] mention plumber: https://www.rplumber.io/docs/docker/

Sources of these: https://www.rdocumentation.org/search?q=docker&packagePage=1&functionPage=4

**Comment by bhaskarvk** [comment]
FWIW my `docker` package is now on CRAN and I've unit tested it on Linux & Windows and it should also work under Mac, or for that matter every system where python + docker python module and reticulate R packages are available.

**Comment by nuest** [comment]
Thanks @bhaskarvk - and congrats for putting the package on CRAN! I'll add a paragraph on your package and will soon try it out!

**Comment by nuest** [comment]
Some tasks for the next update:

- [ ] review packages from http://rpkg.gepuro.net/ (search for "Docker" and "container")

**Comment by akzaidi** [comment]
Thanks for this super useful post! 

I created a docker image for [Microsoft R Client](https://docs.microsoft.com/en-us/r-server/r-client/what-is-microsoft-r-client) here: [akzaidi/mrclient-docker](https://hub.docker.com/r/akzaidi/mrclient-docker). R Client adds to MRO by including a couple of "ScaleR" machine learning algorithms and packages for parallelization and remote computing.

I'm a docker novice, so please let me know if you see any issues or room for improvement!

**Comment by nuest** [comment]
The last updates collected here will not be included in the blog post anymore. Instead, take a look at the _Rockerverse_ article: https://github.com/nuest/rockerverse-paper/
