### ISSUE TITLE
Add "peer reviewed" icon to publication list

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-project.github.io#2]
There is a boolean value for peer review status in the metadata, so let's visualise it, e.g. with an icon.

``` xml
attribute name="Peer reviewed" language="0" disposition="choicegroup"><data>1571</data><additionalInfo>Nein</additionalInfo></attribute>
```

Potential icons:
- https://octicons.github.com/icon/mortar-board/
- https://octicons.github.com/icon/organization
- https://octicons.github.com/icon/eye

**Comment by 7048730** [comment]
Nice idea. This could also be interesting for the platform. Show icon, if peer reviewed.
I'd prefer optics themed or text-check themed icons

* [Eye](https://octicons.github.com/icon/eye/)
* [Magnifier](https://octicons.github.com/icon/search/) (though rather for search)
* [Telescope](https://octicons.github.com/icon/telescope/)
* [Tasklist](https://octicons.github.com/icon/tasklist/)
* [Checklist](https://octicons.github.com/icon/checklist/)
* [Verified](https://octicons.github.com/icon/verified/)

**Comment by nuest** [comment]
"verified" could also be useful for our own verification. Therefore I'd go for "Eye".

OTOH, a verified ERC could also be "Checklist"

**Comment by nuest** [comment]
![image](https://user-images.githubusercontent.com/1325054/53292108-312f2d00-37be-11e9-99ea-85d50c63813c.png)
