### ISSUE TITLE
Use caching in GitHub action

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-project.github.io#79]
Longest step is installing of the gems.

**Comment by nuest** [comment]
@Fmazin Yes, it would be great if you could give this a quick try - it should be possible to speed up the page build quite a lot.

**Comment by Fmazin** [comment]
I have tested the cache action and seems to save around 3 minutes. The runs on my fork can be seen [here](https://github.com/Fmazin/o2r-project.github.io/actions). If this is fine i will prepare an PR.

**Comment by nuest** [comment]
Yes - that's fine! Thank you!
